import = [
    "~/.config/alacritty/themes/themes/afterglow.toml"
]

[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "None"
decorations_theme_variant = "Dark"

[font]
normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"
size = 12.0

[mouse]
hide_when_typing = true
