
" Cursor
set guicursor=

" Line Numbers
set relativenumber
set number

set mouse=a

" Indentation
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smartindent

set list
set listchars=tab:»\ ,space:·,trail:·,nbsp:␣
set nowrap
set timeoutlen=1000
set inccommand=split
set cursorline

" Search
set smartcase
set nohlsearch
set incsearch

" Appearance
set termguicolors
set signcolumn=yes
set colorcolumn=80

" Behavior
set backspace=indent,eol,start
set splitright
set splitbelow
set noswapfile
set nobackup
set undofile
set updatetime=50
set scrolloff=8

" Spellcheck
set spelllang=en_us
set spell

" Folding
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
set foldlevel=9999

" Clipboard
set clipboard+=unnamedplus

" Set leader key to space
let mapleader=" "
let maplocalleader=" "

" Text operations
nnoremap x "_x

" Search and replace
nnoremap <leader>s :%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>

" Move Lines UP and DOWN
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" Join lines without moving cursor
nnoremap J mzJ`z
nnoremap U i<Enter><Esc>

" Split lines without moving cursor
nnoremap K :s/\v(%#\_.{-})/\1\r

" Toggle file explorer
nnoremap <leader>ee :Ex<CR>

" [[ Basic Autocommands ]]
augroup kickstart-highlight-yank
  autocmd!
  autocmd TextYankPost * silent! lua vim.highlight.on_yank()
augroup END

augroup group_cdpwd
  autocmd!
  autocmd VimEnter * silent! lcd %:p:h
augroup END

" netrw
let g:netrw_banner = 0
let g:netrw_winsize = 15
let g:netrw_liststyle = 3
let g:netrw_browse_split = 0
let g:netrw_list_depth = 999

