######################################
###############hypridle###############
######################################
$lock = pidof hyprlock || hyprlock                # avoid starting multiple hyprlock instances.
$lockSession = loginctl lock-session              # lock screen
$dpmsOn = hyprctl dispatch dpms on                # detect activity
$dpmsOff =  hyprctl dispatch dpms off             # screen blank
$suspend = systemctl suspend                      # suspend pc
$min5 = 300
$min5-5 = 330
$min30 = 1800

######################################
###############hyprlock###############
######################################

$text_color = rgba(ede0deFF)
$entry_background_color = rgba(130F0F11)
$entry_border_color = rgba(a08c8955)
$entry_color = rgba(d8c2bfFF)
$font_family = Gabarito
$font_family_clock = Gabarito
$font_material_symbols = Material Symbols Rounded

