source = ~/.config/hypr/hyprEnvVars.conf

general {
    lock_cmd = $lock
    before_sleep_cmd = $lockSession
    after_sleep_cmd = $dpmsOn
}

listener {
    timeout = $min5
    on-timeout = $lockSession
}

listener {
    timeout = $min5-5
    on-timeout = $dpmsOff
    on-resume = $dpmsOn
}

# listener {
#     timeout = $min30
#     on-timeout = $suspend
# }
