
# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

export PATH=$PATH:$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/games:/usr/local/games:/snap/bin

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH=$PATH:$GOPATH/bin
export PATH="$HOME/.deno/bin:$PATH"

# Custom Variables
export EDITOR=nvim
export VISUAL=nvim
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export QT_QPA_PLATFORM=xcb
export BAT_CONFIG_PATH="~/.config/bat/config"
export WALLPAPER_BACKEND=hyprpaper
export CMAKE_TOOLCHAIN_FILE=~/.config/cmake/CMakeToolchain.cmake

# cargo env
[ -f ~/.cargo/env ] && source $HOME/.cargo/env

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
if ! command -v pyenv &> /dev/null
then
    curl https://pyenv.run | bash
fi

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zshhistory
setopt appendhistory

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' # for caseinsensite tab completion

# start tmux
[ -z "$TMUX" ] && exec tmux


# Custom ZSH Binds

# Navigation:
bindkey "\e[1;5D" backward-word        # Ctrl + Left Arrow: Move backward one word
bindkey "\e[1;5C" forward-word         # Ctrl + Right Arrow: Move forward one word

# History Search:
bindkey "^[[A" history-beginning-search-backward   # Up Arrow: Search backward through history
bindkey "^[[B" history-beginning-search-forward    # Down Arrow: Search forward through history
bindkey "^[[A" history-search-backward             # Up Arrow: Search backward through history (alternate)
bindkey "^[[B" history-search-forward              # Down Arrow: Search forward through history (alternate)

# Text Manipulation:
bindkey "\e[3;5~" kill-word               # Ctrl + Del: Delete word after cursor
bindkey "\C-_"    backward-kill-word      # Ctrl + Backspace: Delete word before cursor
bindkey "\e[3~" delete-char                # Delete: Delete character under cursor

# Line Navigation:
bindkey "\e[H"  beginning-of-line         # Home: Move to beginning of line
bindkey '^A' beginning-of-line            # Ctrl + A: Move to beginning of line
bindkey "\e[F"  end-of-line               # End: Move to end of line
bindkey '^E' end-of-line                  # Ctrl + E: Move to end of line

# Load device specific configurations
[ -f "$HOME/.device_config" ] && source "$HOME/.device_config"

# Load functions
[ -f "$HOME/.functionsrc" ] && source "$HOME/.functionsrc"

# Load aliases and shortcuts if existent.
[ -f "$HOME/.aliasrc" ] && source "$HOME/.aliasrc"

# special aliases
alias reload='source ~/.zshrc && clear'
alias frm=frm
alias ex=ex
alias plugins='vim ~/.config/zsh/plugins_config.zsh'
alias tmuxClean=kill_tmux_sessions

# plugins for zsh
[ -f "$HOME/.config/zsh/plugins_config.zsh" ] && source "$HOME/.config/zsh/plugins_config.zsh"

# starship
eval "$(starship init zsh)"
