
# Enable colors and change prompt:
autoload -U colors && colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

export PATH=$PATH:$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/games:/usr/local/games:/snap/bin

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.npm-global/bin:$PATH"

export PATH="$HOME/.deno/bin:$PATH"

# Custom Variables
export EDITOR=nvim
export VISUAL=nvim

# cargo env
[ -f ~/.cargo/env ] && source $HOME/.cargo/env

# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zshhistory
setopt appendhistory

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)               # Include hidden files.
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' # for caseinsensite tab completion

# Custom ZSH Binds
bindkey '^ ' autosuggest-accept
bindkey "\e[1;5D" backward-word
bindkey "\e[1;5C" forward-word
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
bindkey "^[[A" history-search-backward
bindkey "^[[B" history-search-forward

# ctrl-bs and ctrl-del
bindkey "\e[3;5~" kill-word
bindkey "\C-_"    backward-kill-word

# del, home and end
bindkey "\e[3~" delete-char
bindkey "\e[H"  beginning-of-line
bindkey "\e[F"  end-of-line

### functions for aliasrc

# # ex - archive extractor
# # usage: ex <file>
ex ()
{
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1   ;;
            *.tar.gz)    tar xzf $1   ;;
            *.tar.xz)    tar xJf $1   ;;
            *.bz2)       bunzip2 $1   ;;
            *.rar)       unrar x $1     ;;
            *.gz)        gunzip $1    ;;
            *.tar)       tar xf $1    ;;
            *.tbz2)      tar xjf $1   ;;
            *.tgz)       tar xzf $1   ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1;;
            *.7z)        7z x $1      ;;
            *)           echo "'$1' cannot be extracted via ex()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

gt-push() {
    git add .
    git commit -m "$*"
    git pull
    git push
}

pack_man(){
    if [ -x "$(command -v apk)" ];then
        alias pkm='sudo apk add --no-cache '
        elif [ -x "$(command -v apt-get)" ];then
        alias pkm='sudo apt install '
        alias rpkm='sudo apt remove'
        alias rpkmcleanup='sudo apt autoremove'
        alias packdate='sudo apt -y update && flatpak -y --noninteractive update'
        elif [ -x "$(command -v dnf)" ];then
        alias pkm='sudo dnf install '
        alias rpkm='sudo dnf remove '
        alias rpkmcleanup='sudo dnf -y autoremove'
        alias packdate='sudo dnf -y upgrade --refresh'
        elif [ -x "$(command -v zypper)" ];then
        alias pkm='sudo zypper install '
        elif [ -x "$(command -v paru)" ];then
        alias pkm="paru -S "
        alias rpkm='paru -Rdd'
        alias pacman-update='sudo pacman-mirrors --geoip'
        alias rpkmcleanup='paru -Rns $(paru -Qdtq)' # Cleanup orphaned packages
        alias fixpacman="sudo rm /var/lib/pacman/db.lck"
        alias pkmgrade='paru --noconfirm -Syu && sudo flatpak -y --noninteractive update'
        # get fastest mirrors
        alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
        alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
        alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
        alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
        elif [ -x "$(command -v nix-env)" ]; then
        # Nix package manager
        alias pkm='nix-env -iA'
        alias rpkm='nix-env -e'
        alias rpkmcleanup='nix-collect-garbage -d'
        alias packdate='nix-channel --update'
    else
        echo 'This Distro is not supported!'
    fi
}

function frm {
    read -p "Are you sure you want to delete? (y/n): " -k response
    if [[ "$response" == "y" || "$response" == "Y" ]]; then
        rm -rf "$@"
    else
        echo "Aborted."
    fi
}


pack_man
export ex

### End of functions

# Load aliases and shortcuts if existent.
[ -f "$HOME/.config/zsh/aliasrc" ] && source "$HOME/.config/zsh/aliasrc"

# special aliases
alias reload='source ~/.zshrc && clear && source ~/.config/zsh/aliasrc && clear'
alias frm=frm
alias plugins='vim ~/.config/zsh/plugins_config.zsh'

# plugins for zsh
[ -f "$HOME/.config/zsh/plugins_config.zsh" ] && source "$HOME/.config/zsh/plugins_config.zsh"

# starship
eval "$(starship init zsh)"
