---
- name: Configure alacritty
  hosts: localhost
  tasks:
    - name: Ensure alacritty directory exists
      file:
        path: ~/.config/alacritty/
        state: directory
        mode: '0755'

    - name: Copy alacritty configuration
      copy:
        src: alacritty.toml
        dest: ~/.config/alacritty/alacritty.toml

    - name: Ensure themes directory exists
      file:
        path: ~/.config/alacritty/themes
        state: directory
        mode: '0755'

    - name: Download alacritty themes from GitHub
      git:
        repo: 'https://github.com/alacritty/alacritty-theme.git'
        dest: /tmp/alacritty-theme
        version: main

    - name: Copy themes to alacritty themes directory
      copy:
        src: /tmp/alacritty-theme/themes/
        dest: ~/.config/alacritty/themes/
        remote_src: yes

    - name: Clean up temporary files
      file:
        path: /tmp/alacritty-theme
        state: absent
