#!/bin/sh

# Import Wayland display into user environment
systemctl --user import-environment WAYLAND_DISPLAY

# Restart xdg-desktop-portal services
systemctl --user restart xdg-desktop-portal-wlr.service
systemctl --user restart xdg-desktop-portal.service

# Source other configuration files
# The order generally matters for dependencies (e.g., config before keybindings)
. "$HOME/.config/river/config.sh" || echo "Warning: config.sh not found!" >&2
. "$HOME/.config/river/keybindings.sh" || echo "Warning: keybindings.sh not found!" >&2
. "$HOME/.config/river/autostart.sh" || echo "Warning: autostart.sh not found!" >&2
. "$HOME/.config/river/rules.sh" || echo "Warning: rules.sh not found!" >&2

. "$HOME/.config/river/idle.sh" || echo "Warning: idle.sh not found!" >&2

# Monitor configuration
riverctl spawn 'mako > "/tmp/mako.${XDG_VTNR}.${USER}.log" 2>&1 &'
riverctl spawn 'way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &'

work_monitor_left="DP-1"
work_monitor_middle="HDMI-A-1"
work_monitor_right="DP-2"
# Live wallpaper
riverctl spawn 'swww-daemon'
WALLPAPERPATH="/home/floork/dotfiles/configs/live-wallpapers/"
riverctl spawn 'swww img "${WALLPAPERPATH}$(ls "${WALLPAPERPATH}" | shuf -n 1)"'

wlr-randr --output "$work_monitor_left" --mode 1920x1080 --pos 0x0 --transform normal
wlr-randr --output "$work_monitor_middle" --mode 2560x1440 --pos 1920x0 --transform normal
wlr-randr --output "$work_monitor_right" --mode 1920x1080 --pos 4480x0 --transform normal
